blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment, name='add_comment_to_post'),
    url(r'^post/(?P<pk>\d+)/exeadd/$', views.exe_add, name='add_exe_to_task'),
    url(r'^emplist/$', views.emp_list, name='emplist'),
    url(r'^studlist/$', views.stud_list, name='studlist'),
    url(r'^about/$', views.about, name='about'),
    url(r'^studprofile/(?P<pk>\d+)/$', views.stud_profile, name='studprofile'),
    url(r'^employprofile/(?P<pk>\d+)/$', views.employ_profile, name='employprofile'),
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class TaskCategory(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категория'



class UserExtendent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    STUDENT = 'ST'
    EMPLOYEER = 'EM'
    CATEGORY_CHOICES = (
        (STUDENT, 'Студент'),
        (EMPLOYEER, 'Работодатель'),
    )

    category = models.CharField(max_length=40,
                                choices=CATEGORY_CHOICES, blank=True)

    name = models.TextField(max_length=100, blank=True)
    desc = models.TextField(max_length=500, blank=True)
    location = models.TextField(max_length=250, blank=True)
    phone = models.CharField(max_length=12, blank=True)
    email = models.EmailField(blank=True)
    education = models.TextField(max_length=250, blank=True)
    kurs = models.IntegerField(max_length=1, blank=True, default=0)


# @receiver(post_save, sender=User)
# def create_userext(sender, instance, created, **kwargs):
#     if created:
#         UserExtendent.objects.create(user=instance)
#
# @receiver(post_save, sender=User)
# def save_userext(sender, instance, **kwargs):
#     instance.userext.save()

@receiver(post_save, sender=User)
def new_user(sender, instance, created, **kwargs):
    if created:
        UserExtendent.objects.create(user=instance)
    instance.userextendent.save()


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    approve_comment = models.BooleanField(default=False)
    text = models.TextField()
    add_date = models.DateTimeField(default=timezone.now)

    def approve(self):
        self.approve_comment = True
        self.save()

    def __str__(self):
        return self.text



class Post(models.Model):
    ARCHITECT = 'AR'
    VIDEO = 'VI'
    MARKETING = 'MA'
    MUSIC = 'MU'
    DESIGN = 'DE'
    PROGRAMM = 'PR'
    PHOTO = 'PH'
    ENGINEER = 'EN'
    MANAGE = 'MG'

    CATEGORY_CHOICES = (
        (ARCHITECT, 'Архитектура'),
        (VIDEO, 'Видео'),
        (MARKETING, 'Маркетинг'),
        (MUSIC, 'Музыка'),
        (DESIGN, 'Дизайн'),
        (PROGRAMM, 'IT и программирование'),
        (PHOTO, 'Фотография'),
        (ENGINEER, 'Инженерия'),
        (MANAGE, 'Менеджмент'),
    )

    excategory = models.CharField(max_length=40,
                                choices=CATEGORY_CHOICES, blank=True, null=True,)

    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    category = models.ForeignKey(TaskCategory, blank=True, null=True, default=None)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)
    executor = models.ManyToManyField(UserExtendent)
    isactive = models.BooleanField(default=True, blank=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()


    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post, Comment
from .models import UserExtendent
from django.contrib.auth.forms import UserCreationForm

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'excategory', 'text',)

class SignUpForm(UserCreationForm):

    desc = forms.CharField(max_length=500)
    location = forms.CharField(max_length=250)
    phone = forms.CharField(max_length=13)
	adress = forms.AddresField(max_length=2300
    class Meta:
        model = User
        fields = ('username', 'desc', 'location', 'phone', 'email', 'password1', 'password2', )

class CommentsForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
from django.shortcuts import render
from .models import Post, Comment
from .models import UserExtendent
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from .forms import PostForm, SignUpForm, CommentsForm
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login


def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/post_list.html', {'posts':posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
           # post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def deactivate_task(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # post.executor = request.user
    # post.save()
    post.isactive = False
    return redirect('post_list')

@login_required
def exe_add(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # post.executor = request.user
    # post.save()
    post.executor.add(request.user.userextendent)
    return redirect('post_list')

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post_list')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.userextendent.desc = form.cleaned_data.get('desc')
            user.userextendent.location = form.cleaned_data.get('location')
            user.userextendent.phone = form.cleaned_data.get('phone')
            user.userextendent.email = form.cleaned_data.get('email')
            user.save()
            my_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=my_password)
            login(request, user)
            return redirect('post_list')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentsForm()
    return render(request, 'blog/add_comment.html', {'form': form})

def emp_list(request):
    employers = UserExtendent.objects.filter(category='EM')
    return render(request, 'blog/emplist.html', {'employers': employers})

def stud_list(request):
    students = UserExtendent.objects.filter(category='ST')
    return render(request, 'blog/studlist.html', {'students': students})

def stud_profile(request, pk):
    student = get_object_or_404(UserExtendent, pk=pk)
    return render(request, 'blog/studprofile.html', {'student': student})

def employ_profile(request, pk):
    employ = get_object_or_404(UserExtendent, pk=pk)
    return render(request, 'blog/employprofile.html', {'employ': employ})

def about(request):
    about = UserExtendent.objects.filter(category='ST')
    return render(request, 'blog/about.html', {'about': about})

# def employ_profile_list(request):
#     emposts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
#     return render(request, 'blog/employprofile.html', {'emposts':emposts})

blog/templates/blog/about.html
<!DOCTYPE html lang="en-US">
{% load staticfiles %}
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<title>Student Hunter</title>

<link rel='stylesheet' id='reset-css'   href="{% static 'css/reset.css' %}" type='text/css' media='all' />
<link rel='stylesheet' id='superfish-css'  href="{% static 'css/superfish.css' %}" type='text/css' media='all' />
<link rel='stylesheet' id='fontawsome-css'  href='css/font-awsome/css/font-awesome.css' type='text/css' media='all' />
<link rel='stylesheet' id='orbit-css-css'  href="{% static 'css/orbit.css' %}" type='text/css' media='all' />
<link rel='stylesheet' id='style-css'  href="{% static 'css/style.css' %}" type='text/css' media='all' />
<link rel='stylesheet' id='color-scheme-css'  href='css/color/green.css' type='text/css' media='all' />
<link rel="stylesheet" href="{% static 'css/zerogrid.css' %}" type="text/css" media="screen">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}" type="text/css" media="screen">
{#    <link rel="stylesheet" href="{% static 'css/blog.css' %}">#}

<script type='text/javascript' src="{% static 'js/jquery.js' %}"></script>
<script type='text/javascript' src="{% static 'js/jquery-migrate.min.js' %}"></script>
<script type='text/javascript' src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<script type='text/javascript' src="{% static 'js/jquery.carouFredSel-6.2.1-packed.js' %}"></script>
<script type='text/javascript' src="{% static 'js/hoverIntent.js' %}"></script>
<script type='text/javascript' src="{% static 'js/superfish.js' %}"></script>
<script type='text/javascript' src="{% static 'js/orbit.min.js' %}"></script>
<script src="{% static "js/css3-mediaqueries.js" %}"></script>
<script type="text/javascript" language="javascript">
	$(function() {

		/* Start Carousel */
		$('#featured-posts').carouFredSel({
			auto: true,
					prev: '#prev2',
					next: '#next2',
		});
		/* End Carousel */


		/* Start Orbit Slider */
		$(window).load(function() {
			$('.post-gallery').orbit({
				animation: 'fade',
			});
		});
		/* End Orbit Slider */


		/* Start Super fish */
		jQuery(document).ready(function(){
			jQuery('ul.sf-menu').superfish({
				delay:         100,
				speed:         'fast',
				speedOut:      'fast',
			});
		});
		/* End Of Super fish */

	});
</script>
</head>

<body class="single single-post postid-49 single-format-standard">

	<!-- Start Header -->
    <div class="container zerogrid">
        <div class="col-full"><div class="wrap-col">
        	<div id="header-nav-container">

                    <a href="/">
                    <img src="{% static "images/logo.png" %}" id="logo" />
                    </a>

					<!-- Navigation Menu -->

	<ul class="sf-menu">
        <li class="menu-item"><a href="{% url 'emplist' %}">Компании</a></li>
        <li class="menu-item"><a href="{% url 'studlist' %}">Студенты</a></li>
	<li class="menu-item"><a href="blog.html">Контакты</a></li>
<li class="menu-item"><a href="#">Профиль</a>
</li>
                    <!-- End Navigation Menu -->

                    <div class="clear"></div>

            </div>
			</div>
        </div>
    <div class="clear"></div>
    </div>
    <div class="spacing-30"></div>
    <!-- End Header -->


    <!-- Start Main Container -->
    <!-- Start Main Container -->
    <div class="container zerogrid">

    <div class="col-full page-conainer">
	<div class="wrap-col">
    <div class="post-margin">
    <h5 class="page-title">Student Hunter</h5>

    <!-- Start Entry -->
        <p>Сергеев Сергей Николаевич</p>
        <p>792786534066</p>
    <p>     В современном мире высшее образование является одним из важнейших атрибутов человека. Выпускники школ в поисках перспективы и развития выбирают высшее образование, ведь именно оно дает возможность устроиться на высокооплачиваемую и престижную работу. Не смотря на большие возможности, которые дает высшее образование, оно вовсе не гарантирует необходимый уровень знаний и трудоустройство.
	Образование в высших образовательных учреждениях прививает человеку самые разные навыки, которые помогут ему не только стать профессионалом в своей области, но всесторонне развиваться как личность. Для того, чтобы на своем пути преодолевать препятствия и достигать своих целей в карьерной лестнице, выпускник должен владеть прочным фундаментом необходимых навыков и знаний. Однако, не редкость, когда преподаватели подают своим студентам, материал, утративший свою актуальность вместо того, что действительно необходимо. Помимо этого, и сами образовательные программы могут отличаться от современный реалий, особенно в быстро развивающихся сферах жизни. Стоит так же отметить, что подготовка специалистов в рамках всей образовательной системы плохо ориентирована на получение студентами реального опыта по изучаемой специальности.
</p>


<div class="symple-clear-floats"></div>
    <!-- End Entry -->

    </div>
	</div>
    </div>

    <div class="clear"></div>
        </div>
	<!-- End Main Container -->













	<!-- End Main Container -->


    <!-- Start Footer -->
    <div class="spacing-30"></div>
    <div class="container zerogrid">
        <div id="footer-container" class="col-full">
        <div class="wrap-col">
            <!-- Footer Copyright -->
            <p>Copyrigh &copy; Cергеев Сергей</p>
            <!-- End Footer Copyright -->

            <!-- Footer Logo -->

            <!-- End Footer Logo -->

        <div class="clear"></div>
		</div>
        </div>
    </div>
    <!-- End Footer -->


</body>

</html>

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{#{% extends 'blog/base.html' %}#}
{##}
{#{% block content %}#}
{#    <h1>New post</h1>#}
{#    <form method="POST" class="post-form">{% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit" class="save btn btn-default">Save</button>#}
{#    </form>#}
{#{% endblock %}#}







<!DOCTYPE html lang="en-US">
{% load staticfiles %}
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<title>Euclid Free Responsive Html5 Themes</title>

<link rel='stylesheet' id='reset-css'   href="{% static 'css/reset.css' %}" type='text/css' media='all' />
<link rel='stylesheet' id='superfish-css'  href="{% static 'css/superfish.css' %}" type='text/css' media='all' />
<link rel='stylesheet' id='fontawsome-css'  href='css/font-awsome/css/font-awesome.css' type='text/css' media='all' />
<link rel='stylesheet' id='orbit-css-css'  href="{% static 'css/orbit.css' %}" type='text/css' media='all' />
<link rel='stylesheet' id='style-css'  href="{% static 'css/style.css' %}" type='text/css' media='all' />
<link rel='stylesheet' id='color-scheme-css'  href='css/color/green.css' type='text/css' media='all' />
<link rel="stylesheet" href="{% static 'css/zerogrid.css' %}" type="text/css" media="screen">
<link rel="stylesheet" href="{% static 'css/responsive.css' %}" type="text/css" media="screen">
<script type='text/javascript' src="{% static 'js/jquery.js' %}"></script>
<script type='text/javascript' src="{% static 'js/jquery-migrate.min.js' %}"></script>
<script type='text/javascript' src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<script type='text/javascript' src="{% static 'js/jquery.carouFredSel-6.2.1-packed.js' %}"></script>
<script type='text/javascript' src="{% static 'js/hoverIntent.js' %}"></script>
<script type='text/javascript' src="{% static 'js/superfish.js' %}"></script>
<script type='text/javascript' src="{% static 'js/orbit.min.js' %}"></script>
<script src="{% static "js/css3-mediaqueries.js" %}"></script>

<script type="text/javascript" language="javascript">
	$(function() {

		/* Start Carousel */
		$('#featured-posts').carouFredSel({
			auto: true,
					prev: '#prev2',
					next: '#next2',
		});
		/* End Carousel */


		/* Start Orbit Slider */
		$(window).load(function() {
			$('.post-gallery').orbit({
				animation: 'fade',
			});
		});
		/* End Orbit Slider */


		/* Start Super fish */
		jQuery(document).ready(function(){
			jQuery('ul.sf-menu').superfish({
				delay:         100,
				speed:         'fast',
				speedOut:      'fast',
			});
		});
		/* End Of Super fish */

	});
</script>
</head>

<body class="single single-post postid-49 single-format-standard">

	<!-- Start Header -->
    <div class="container zerogrid">
        <div class="col-full"><div class="wrap-col">
        	<div id="header-nav-container">

                    <a href="/">
                    <img src="{% static "images/logo.png" %}" id="logo" />
                    </a>

					<!-- Navigation Menu -->

	<ul class="sf-menu">
        <li class="menu-item"><a href="{% url 'emplist' %}">Компании</a></li>
        <li class="menu-item"><a href="{% url 'studlist' %}">Студенты</a></li>
	<li class="menu-item"><a href="blog.html">Контакты</a></li>
<li class="menu-item"><a href="#">Профиль</a>
</li>
                    <!-- End Navigation Menu -->

                    <div class="clear"></div>

            </div>
			</div>
        </div>
    <div class="clear"></div>
    </div>
    <div class="spacing-30"></div>
    <!-- End Header -->
    <!-- End Header -->


    <!-- Start Main Container -->
    <div class="container zerogrid">

        <!-- Start Posts Container -->
        <div class="col-2-3" id="post-container">
        	<div class="wrap-col">


			<!-- Comments -->
            <div class="comment-container">

            <h6 id="comment-header">Добавление задачи</h6>

            <ul class="comment-list">
                        </ul>


            <!-- Comment Form -->
            <div class="commen-form">
            								<div id="respond" class="comment-respond">
				<h3 id="reply-title" class="comment-reply-title"> <small><a rel="nofollow" id="cancel-comment-reply-link" href="#" style="display:none;">Cancel Reply</a></small></h3>
									<form action="" method="post" id="comment-form-container" class="comment-form">
																			<p class="comment-notes"></p>



                                        <form method="POST" class="post-form">{% csrf_token %}
{#                                        {{ form.as_p }}#}

<br>
                                            <label for="comment">Заголовок: </label>
                                            <br>
                                            <input id="title" type="text" name="title" value="{{ title }} " style="width: 100%; height: 30px;"  >


<br>
                                            <br>
                                            <label for="email">Категория: </label>
                                            <br>

                                            <select name="excategory" style="width: 100%; height: 30px;" required="" id="id_category">
                                                  <option value="" selected="">---------</option>
                                                  <option value="AR">Архитектура</option>
                                                  <option value="VI">Видео</option>
                                                  <option value="MA">Маркетинг</option>
                                                  <option value="MU">Музыка</option>
                                                    <option value="DE">Дизайн</option>
                                                    <option value="PR">IT и программирование</option>
                                                    <option value="PH">Фотография</option>
                                                    <option value="EN">Инженерия</option>
                                                <option value="MG">Менеджмент</option>

                                            </select>



                                                <br>
                                            <br>
                                                <label for="comment">Текст: </label>
                                            <br>
                                                <input id="text" type="text" name="text" value="{{ text }}" style="width: 100%; height: 150px;">





{#                                        <button type="submit" class="save btn btn-default">Save</button>#}
{#                                        </form>#}

                                        <p class="form-allowed-tags"></p>						<p class="form-submit">
							<input name="submit" type="submit" id="comment-submit" value="Опубликовать" />
							<input type='hidden' name='comment_post_ID' value='49' id='comment_post_ID' />
<input type='hidden' name='comment_parent' id='comment_parent' value='0' />
						</p>
											</form>
							</div><!-- #respond -->
			            <div class="clear"></div>
            </form>
            </div>
            <!-- End Comment Form -->

            </div>
            <!-- End Comments -->


        <div class="clear"></div>
		</div>
        </div>
        <!-- End Posts Container -->

        <!-- Start Sidebar -->
		<div class="col-1-3"><div class="wrap-col">
			<div class="widget-container"><h6 class="widget-title">Категории</h6>		<ul>
	<li class="cat-item cat-item-5"><a href="#" title="View all posts filed under Apps">Архитектура / интерьер</a>
</li>
	<li class="cat-item cat-item-3"><a href="#" title="View all posts filed under Illustration">Видео</a>
</li>
	<li class="cat-item cat-item-4"><a href="#" title="View all posts filed under Logo">Маркетинг и реклама</a>
</li>
<li class="cat-item cat-item-4"><a href="#" title="View all posts filed under Logo">Музыка / звук</a>
</li>
<li class="cat-item cat-item-4"><a href="#" title="View all posts filed under Logo">Дизайн</a>
</li>
<li class="cat-item cat-item-4"><a href="#" title="View all posts filed under Logo">IT и Программирование</a>
</li>
<li class="cat-item cat-item-4"><a href="#" title="View all posts filed under Logo">Фотография</a>
</li>
<li class="cat-item cat-item-4"><a href="#" title="View all posts filed under Logo">Инженерия</a>
</li>
<li class="cat-item cat-item-4"><a href="#" title="View all posts filed under Logo">Менеджмент</a>
</li>
		</ul>
{#    <div class="clear"></div></div><div class="widget-container"><h6 class="widget-title">Последние задачи</h6>	<!-- Start Widget -->#}
{#                    <ul class="widget-recent-posts">#}
{##}
{#                    <li>#}
{#                    <div class="post-image">#}
{#                    <div class="post-mask"></div>#}
{#                    <img width="70" height="70" src="img/HighRes-70x70.jpg" class="attachment-post-widget #"  />                </div>#}
{##}
{#                    <h6><a href="#">Подключить систему онлайн-оплаты на сайт на WP</a></h6>#}
{#                    <span>Ноябрь 02, 2018</span>#}
{#                    <div class="clear"></div>#}
{#                    </li>#}
{##}
{##}
{#                    <li>#}
{#                    <div class="post-image">#}
{#                    <div class="post-mask"></div>#}
{#                    <img width="70" height="70" src="img/one-more-beer-70x70.png" class="attachment-post-widget #"  />                </div>#}
{##}
{#                    <h6><a href="#">Перевод планов здания AUTOCAD</a></h6>#}
{#                    <span>Ноябрь 02, 2018</span>#}
{#                    <div class="clear"></div>#}
{#                    </li>#}
{##}
{##}
{#                    <li>#}
{#                    <div class="post-image">#}
{#                    <div class="post-mask"></div>#}
{#                    <img width="70" height="70" src="img/Port_Harbor1-70x70.jpg" class="attachment-post-widget #"  />                </div>#}
{##}
{#                    <h6><a href="#">НАСТРОИТЬ ANALYTICS GOOGLE</a></h6>#}
{#                    <span>Ноябрь 02, 2018</span>#}
{#                    <div class="clear"></div>#}
{#                    </li>#}
{##}
{##}
{#                    <li>#}
{#                    <div class="post-image">#}
{#                    <div class="post-mask"></div>#}
{#                    <img width="70" height="70" src="img/Timothy-J-Reynolds-2560x14401-70x70.jpg" class="attachment-post-widget #"  />                </div>#}
{##}
{#                    <h6><a href="#">РАЗРАБОТАТЬ СТАНОК</a></h6>#}
{#                    <span>Ноябрь 02, 2018</span>#}
{#                    <div class="clear"></div>#}
{#                    </li>#}
{##}
{##}
{#                    </ul>#}
   <!-- End Widget -->
<div class="clear"></div></div>
    <div class="clear"></div>
</div></div>        <!-- End Sidebar -->

    <div class="clear"></div>
    </div>
	<!-- End Main Container -->


    <!-- Start Footer -->
    <div class="spacing-30"></div>
    <div class="container zerogrid">
        <div id="footer-container" class="col-full">
        <div class="wrap-col">
            <!-- Footer Copyright -->
            <p>Copyrigh &copy; Cергеев Сергей</p>
            <!-- End Footer Copyright -->

            <!-- Footer Logo -->

            <!-- End Footer Logo -->

        <div class="clear"></div>
		</div>
        </div>
    </div>
    <!-- End Footer -->


</body>

</html>